name: Bambu 3MF Importer Auto Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: Package add-on into zip
        run: |
          mkdir -p dist/3mf_import_and_color_split
          cp __init__.py import_3mf_vertex_colored.py import_3_mf_color.py README.md dist/3mf_import_and_color_split/
          cd dist
          zip -r 3mf_import_and_color_split.zip 3mf_import_and_color_split


      - name: 🕓 Get current timestamp
        id: timestamp
        run: echo "time=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: 📝 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Auto Release - ${{ steps.timestamp.outputs.time }}"
          tag_name: "auto-${{ steps.timestamp.outputs.time }}"
          files: dist/3mf_import_and_color_split.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
